---
title: "R Notebook"
---

This notebook contains plots/results shared in the AAFS 2022 presentation


```{r setup}
library(tidyverse)
library(cmcR)
library(x3ptools)
source("~/cmas/cmas Functions/cmasFunctions.R")
```



```{r}
# for the sake of illustration, preprocess the Fadul scans using different
# gaussian filter parameters
future:::ClusterRegistry("stop")

future::plan(future::multisession(workers = future::availableCores() - 6))

scans_notFiltered <- 
  furrr::future_map(list.files("~/nbtrdScans/fadulScans/",full.names = TRUE,pattern = ".x3p",include.dirs = TRUE,recursive = TRUE),
                    function(file){
                      
                      dat <- x3p_read(file)
                      
                      
                      # maskBackground <- unique(c(dat$mask))[1]
                      # 
                      # if(all(str_length(unique(as.vector(dat$mask))) > 7) & !any(str_detect(unique(as.vector(dat$mask)),"FF$"))){
                      #   
                      #   maskBackground <- paste0(maskBackground,"FF")
                      #   
                      # }
                      
                      dat <- dat %>%
                        preProcess_crop(region = "exterior",
                                        radiusOffset = -30) %>%
                        preProcess_crop(region = "interior",
                                        radiusOffset = 200) %>%
                        preProcess_removeTrend(statistic = "quantile",
                                               tau = .5,
                                               method = "fn") %>%
                        # preProcess_gaussFilter() %>%
                        x3ptools::sample_x3p()
                      
                      dat <- dat %>%
                        preProcess_cropWS(robust = FALSE,
                                          croppingProp = .5)
                      
                      dat$mask <- NULL
                      
                      return(dat)
                      
                    })

future:::ClusterRegistry("stop")

future::plan(future::multisession(workers = future::availableCores() - 6))

scans_filtered_32 <- 
  furrr::future_map(list.files("~/nbtrdScans/fadulScans/",full.names = TRUE,pattern = ".x3p",include.dirs = TRUE,recursive = TRUE),
                    function(file){
                      
                      dat <- x3p_read(file)
                      
                      
                      # maskBackground <- unique(c(dat$mask))[1]
                      # 
                      # if(all(str_length(unique(as.vector(dat$mask))) > 7) & !any(str_detect(unique(as.vector(dat$mask)),"FF$"))){
                      #   
                      #   maskBackground <- paste0(maskBackground,"FF")
                      #   
                      # }
                      
                      dat <- dat %>%
                        preProcess_crop(region = "exterior",
                                        radiusOffset = -30) %>%
                        preProcess_crop(region = "interior",
                                        radiusOffset = 200) %>%
                        preProcess_removeTrend(statistic = "quantile",
                                               tau = .5,
                                               method = "fn") %>%
                        preProcess_gaussFilter(wavelength = c(32),filtertype = "lp") %>%
                        x3ptools::sample_x3p()
                      
                      dat <- dat %>%
                        preProcess_cropWS(robust = FALSE,
                                          croppingProp = .5)
                      
                      dat$mask <- NULL
                      
                      return(dat)
                      
                    })

future:::ClusterRegistry("stop")

future::plan(future::multisession(workers = future::availableCores() - 6))

scans_filtered_bp <- 
  furrr::future_map(list.files("~/nbtrdScans/fadulScans/",full.names = TRUE,pattern = ".x3p",include.dirs = TRUE,recursive = TRUE),
                    function(file){
                      
                      dat <- x3p_read(file)
                      
                      
                      # maskBackground <- unique(c(dat$mask))[1]
                      # 
                      # if(all(str_length(unique(as.vector(dat$mask))) > 7) & !any(str_detect(unique(as.vector(dat$mask)),"FF$"))){
                      #   
                      #   maskBackground <- paste0(maskBackground,"FF")
                      #   
                      # }
                      
                      dat <- dat %>%
                        preProcess_crop(region = "exterior",
                                        radiusOffset = -30) %>%
                        preProcess_crop(region = "interior",
                                        radiusOffset = 200) %>%
                        preProcess_removeTrend(statistic = "quantile",
                                               tau = .5,
                                               method = "fn") %>%
                        preProcess_gaussFilter(wavelength = c(32,500),filtertype = "bp") %>%
                        x3ptools::sample_x3p()
                      
                      dat <- dat %>%
                        preProcess_cropWS(robust = FALSE,
                                          croppingProp = .5)
                      
                      dat$mask <- NULL
                      
                      return(dat)
                      
                    })

save(scans_filtered_bp,file = "data/scans_filtered_bp.RData")

save(scans_notFiltered,file = "data/scans_notFiltered.RData")
save(scans_filtered_16,file = "data/scans_filtered_16.RData")
save(scans_filtered_32,file = "data/scans_filtered_32.RData")

x3pListPlot(scans_notFiltered[1:2],type = "list",rotate = 90)
# x3pListPlot(scans_filtered_16[1:2],type = "list")
x3pListPlot(scans_filtered_32[1:2],type = "list",rotate = 90)
x3pListPlot(scans_filtered_bp[1:2],type = "list",rotate = 90)
```


```{r}
#split data into train/test split (set.seed makes this reproducible)
set.seed(1192022)
trainBarrels <- sample(1:10,size = 5)

testBarrels <- seq(1,10)[-trainBarrels]

matchDictionary <- map_dfr(1:10,
                           function(barrel){
                             
                             data.frame(scanName = list.files(paste0("~/nbtrdScans/fadulScans/Fadul_",barrel),
                                                              pattern = ".x3p",include.dirs = FALSE,recursive = TRUE)) %>%
                               mutate(scanName = str_remove(str_remove(scanName,"cc/"),".x3p"),
                                      barrelName = barrel)
                             
                           })

trainScanInds <- data.frame(scanName = str_split(list.files("~/nbtrdScans/fadulScans/",full.names = TRUE,pattern = ".x3p",include.dirs = TRUE,recursive = TRUE),"/") %>%
                              map_chr(~ .[10]) %>%
                              str_remove(".x3p")) %>%
  left_join(matchDictionary,by = "scanName") %>%
  arrange(barrelName) %>%
  mutate(scanInd = 1:nrow(.)) %>%
  filter(barrelName %in% trainBarrels) %>%
  pull(scanInd)

testScanInds <- data.frame(scanName = str_split(list.files("~/nbtrdScans/fadulScans/",full.names = TRUE,pattern = ".x3p",include.dirs = TRUE,recursive = TRUE),"/") %>%
                             map_chr(~ .[10]) %>%
                             str_remove(".x3p")) %>%
  left_join(matchDictionary,by = "scanName") %>%
  arrange(barrelName) %>%
  mutate(scanInd = 1:nrow(.)) %>%
  filter(barrelName %in% testBarrels) %>%
  pull(scanInd)
```

```{r}
surfaceMat_df <- 
  purrr::pmap_dfr(.l = list(scans_notFiltered[trainScanInds],
                            data.frame(scanName = str_split(list.files("~/nbtrdScans/fadulScans/",full.names = TRUE,pattern = ".x3p",include.dirs = TRUE,recursive = TRUE),"/") %>%
                                         map_chr(~ .[10]) %>%
                                         str_remove(".x3p")) %>%
                              left_join(matchDictionary,by = "scanName") %>%
                              arrange(barrelName) %>%
                              mutate(scanInd = 1:nrow(.)) %>%
                              filter(barrelName %in% trainBarrels) %>%
                              pull(scanName),
                            90),
                  function(x3p,name,theta){
                    x3p$surface.matrix <- cmcR:::rotateSurfaceMatrix_noCrop(x3p$surface.matrix,
                                                                            theta = theta + 180) #+180 to stay with what rotate_x3p would output
                    
                    # x3p <- preProcess_cropWS(x3p,croppingProp = .5)
                    
                    x3p$header.info$sizeY <- ncol(x3p$surface.matrix)
                    x3p$header.info$sizeX <- nrow(x3p$surface.matrix)
                    
                    x3p %>%
                      x3ptools::x3p_to_df() %>%
                      dplyr::mutate(value = .data$value - median(.data$value,na.rm = TRUE)) %>%
                      dplyr::mutate(x = .data$x*1e6,
                                    y = .data$y*1e6,
                                    height = .data$value*1e6) %>%
                      dplyr::mutate(x3p = rep(name,times = nrow(.)))
                  }) %>%
  dplyr::mutate(x3p = factor(.data$x3p,levels = data.frame(scanName = str_split(list.files("~/nbtrdScans/fadulScans/",full.names = TRUE,pattern = ".x3p",include.dirs = TRUE,recursive = TRUE),"/") %>%
                                                             map_chr(~ .[10]) %>%
                                                             str_remove(".x3p")) %>%
                               left_join(matchDictionary,by = "scanName") %>%
                               arrange(barrelName) %>%
                               mutate(scanInd = 1:nrow(.)) %>%
                               filter(barrelName %in% trainBarrels) %>%
                               pull(scanName)))

plts <- surfaceMat_df %>%
  ggplot2::ggplot(ggplot2::aes(x = .data$x,y = .data$y)) +
  ggplot2::geom_raster(ggplot2::aes(fill = .data$height))  +
  ggplot2::scale_fill_gradientn(colours =  rev(c('#7f3b08','#b35806','#e08214','#fdb863','#fee0b6','#f7f7f7','#d8daeb','#b2abd2','#8073ac','#542788','#2d004b')),
                                values = scales::rescale(quantile(surfaceMat_df$height,c(0,.01,.025,.1,.25,.5,.75,0.9,.975,.99,1),na.rm = TRUE)),
                                breaks = function(lims){
                                  dat <- quantile(surfaceMat_df$height,c(0,.01,.25,.5,.75,.99,1),na.rm = TRUE)
                                  
                                  dat <- dat %>%
                                    setNames(paste0(names(dat)," [",round(dat,1),"]"))
                                  
                                  return(dat)
                                },
                                na.value = "gray80") +
  ggplot2::coord_fixed(expand = FALSE) +
  ggplot2::theme_minimal() +
  ggplot2::theme(
    axis.title.x = ggplot2::element_blank(),
    axis.text.x = ggplot2::element_blank(),
    axis.ticks.x = ggplot2::element_blank(),
    axis.title.y = ggplot2::element_blank(),
    axis.text.y = ggplot2::element_blank(),
    axis.ticks.y = ggplot2::element_blank(),
    panel.grid.major = ggplot2::element_blank(),
    panel.grid.minor = ggplot2::element_blank(),
    panel.background = ggplot2::element_blank()) +
  ggplot2::guides(fill = ggplot2::guide_colourbar(barheight = grid::unit(2.5,"in"),
                                                  label.theme = ggplot2::element_text(size = 8),
                                                  title.theme = ggplot2::element_text(size = 10),
                                                  frame.colour = "black",
                                                  ticks.colour = "black"),
                  colour = 'none') +
  ggplot2::labs(fill = expression("Rel. Height ["*mu*"m]")) +
  ggplot2::facet_wrap(~ x3p) +
  theme(legend.position = "none")

ggsave(filename = "trainScans_noFilter.png",plot = plts,height = 5,width = 5)
```

```{r}
surfaceMat_df <- 
  purrr::pmap_dfr(.l = list(scans_notFiltered[testScanInds],
                            data.frame(scanName = str_split(list.files("~/nbtrdScans/fadulScans/",full.names = TRUE,pattern = ".x3p",include.dirs = TRUE,recursive = TRUE),"/") %>%
                                         map_chr(~ .[10]) %>%
                                         str_remove(".x3p")) %>%
                              left_join(matchDictionary,by = "scanName") %>%
                              arrange(barrelName) %>%
                              mutate(scanInd = 1:nrow(.)) %>%
                              filter(barrelName %in% testBarrels) %>%
                              pull(scanName),
                            90),
                  function(x3p,name,theta){
                    x3p$surface.matrix <- cmcR:::rotateSurfaceMatrix_noCrop(x3p$surface.matrix,
                                                                            theta = theta + 180) #+180 to stay with what rotate_x3p would output
                    
                    # x3p <- preProcess_cropWS(x3p,croppingProp = .5)
                    
                    x3p$header.info$sizeY <- ncol(x3p$surface.matrix)
                    x3p$header.info$sizeX <- nrow(x3p$surface.matrix)
                    
                    x3p %>%
                      x3ptools::x3p_to_df() %>%
                      dplyr::mutate(value = .data$value - median(.data$value,na.rm = TRUE)) %>%
                      dplyr::mutate(x = .data$x*1e6,
                                    y = .data$y*1e6,
                                    height = .data$value*1e6) %>%
                      dplyr::mutate(x3p = rep(name,times = nrow(.)))
                  }) %>%
  dplyr::mutate(x3p = factor(.data$x3p,levels = data.frame(scanName = str_split(list.files("~/nbtrdScans/fadulScans/",full.names = TRUE,pattern = ".x3p",include.dirs = TRUE,recursive = TRUE),"/") %>%
                                                             map_chr(~ .[10]) %>%
                                                             str_remove(".x3p")) %>%
                               left_join(matchDictionary,by = "scanName") %>%
                               arrange(barrelName) %>%
                               mutate(scanInd = 1:nrow(.)) %>%
                               filter(barrelName %in% testBarrels) %>%
                               pull(scanName)))

plts <- surfaceMat_df %>%
  ggplot2::ggplot(ggplot2::aes(x = .data$x,y = .data$y)) +
  ggplot2::geom_raster(ggplot2::aes(fill = .data$height))  +
  ggplot2::scale_fill_gradientn(colours =  rev(c('#7f3b08','#b35806','#e08214','#fdb863','#fee0b6','#f7f7f7','#d8daeb','#b2abd2','#8073ac','#542788','#2d004b')),
                                values = scales::rescale(quantile(surfaceMat_df$height,c(0,.01,.025,.1,.25,.5,.75,0.9,.975,.99,1),na.rm = TRUE)),
                                breaks = function(lims){
                                  dat <- quantile(surfaceMat_df$height,c(0,.01,.25,.5,.75,.99,1),na.rm = TRUE)
                                  
                                  dat <- dat %>%
                                    setNames(paste0(names(dat)," [",round(dat,1),"]"))
                                  
                                  return(dat)
                                },
                                na.value = "gray80") +
  ggplot2::coord_fixed(expand = FALSE) +
  ggplot2::theme_minimal() +
  ggplot2::theme(
    axis.title.x = ggplot2::element_blank(),
    axis.text.x = ggplot2::element_blank(),
    axis.ticks.x = ggplot2::element_blank(),
    axis.title.y = ggplot2::element_blank(),
    axis.text.y = ggplot2::element_blank(),
    axis.ticks.y = ggplot2::element_blank(),
    panel.grid.major = ggplot2::element_blank(),
    panel.grid.minor = ggplot2::element_blank(),
    panel.background = ggplot2::element_blank()) +
  ggplot2::guides(fill = ggplot2::guide_colourbar(barheight = grid::unit(2.5,"in"),
                                                  label.theme = ggplot2::element_text(size = 8),
                                                  title.theme = ggplot2::element_text(size = 10),
                                                  frame.colour = "black",
                                                  ticks.colour = "black"),
                  colour = 'none') +
  ggplot2::labs(fill = expression("Rel. Height ["*mu*"m]")) +
  ggplot2::facet_wrap(~ x3p) +
  theme(legend.position = "none")

ggsave(filename = "testScans_noFilter.png",plot = plts,height = 5,width = 5)

```


```{r}
scanNames <- str_split(list.files("~/nbtrdScans/fadulScans/",full.names = TRUE,pattern = ".x3p",include.dirs = TRUE,recursive = TRUE),"/") %>%
  map_chr(~ .[[length(.)]]) %>%
  str_remove(".x3p")

# future:::ClusterRegistry("stop")

future::plan(future::multisession(workers = future::availableCores() - 10))

cmcs_notFiltered <- 
  furrr::future_map_dfr(1:(length(scans_notFiltered) - 1),
                        function(refInd){
                          map_dfr((refInd + 1):length(scans_notFiltered),
                                  function(targInd){
                                    
                                    ref <- scans_notFiltered[[refInd]]
                                    targ <- scans_notFiltered[[targInd]]
                                    
                                    CMCs <- purrr::map_dfr(seq(-30,30,by = 3),
                                                           ~ comparison_allTogether(reference = ref,
                                                                                    target = targ,
                                                                                    theta = .))  %>%
                                      mutate(originalMethodClassif = decision_CMC(cellIndex = cellIndex,
                                                                                  x = x,
                                                                                  y = y,
                                                                                  theta = theta,
                                                                                  corr = pairwiseCompCor,
                                                                                  xThresh = 20,
                                                                                  thetaThresh = 6,
                                                                                  corrThresh = .5)) %>%
                                      mutate(comparisonName = paste0(scanNames[refInd]," vs. ",scanNames[targInd]))
                                    
                                    return(CMCs)
                                    
                                  })
                        })

save(cmcs_notFiltered,file = "data/cmcs_notFiltered.RData")

cmcs_filtered_16 <- 
  furrr::future_map_dfr(1:(length(scans_filtered) - 1),
                        function(refInd){
                          map_dfr((refInd + 1):length(scans_filtered),
                                  function(targInd){
                                    
                                    ref <- scans_filtered[[refInd]]
                                    targ <- scans_filtered[[targInd]]
                                    
                                    CMCs <- purrr::map_dfr(seq(-30,30,by = 3),
                                                           ~ comparison_allTogether(reference = ref,
                                                                                    target = targ,
                                                                                    theta = .))  %>%
                                      mutate(originalMethodClassif = decision_CMC(cellIndex = cellIndex,
                                                                                  x = x,
                                                                                  y = y,
                                                                                  theta = theta,
                                                                                  corr = pairwiseCompCor,
                                                                                  xThresh = 20,
                                                                                  thetaThresh = 6,
                                                                                  corrThresh = .5)) %>%
                                      mutate(comparisonName = paste0(scanNames[refInd]," vs. ",scanNames[targInd]))
                                    
                                    return(CMCs)
                                    
                                  })
                        })

save(cmcs_filtered,file = "data/cmcs_filtered.RData")
```

```{r}
list.files("~/nbtrdScans/fadulScans/",full.names = TRUE,pattern = ".x3p",include.dirs = TRUE,recursive = TRUE)

trainFileNames <- data.frame(fileName = list.files("~/nbtrdScans/fadulScans/",full.names = TRUE,pattern = ".x3p",include.dirs = TRUE,recursive = TRUE)) %>%
  mutate(scanName = str_split(fileName,"/") %>%
           map_chr(~ .[10]) %>%
           str_remove(".x3p")) %>%
  left_join(matchDictionary,by = "scanName") %>%
  arrange(barrelName) %>%
  mutate(scanInd = 1:nrow(.)) %>%
  filter(barrelName %in% trainBarrels) %>%
  pull(fileName)

trainScanNames <- data.frame(fileName = list.files("~/nbtrdScans/fadulScans/",full.names = TRUE,pattern = ".x3p",include.dirs = TRUE,recursive = TRUE)) %>%
  mutate(scanName = str_split(fileName,"/") %>%
           map_chr(~ .[10]) %>%
           str_remove(".x3p")) %>%
  left_join(matchDictionary,by = "scanName") %>%
  arrange(barrelName) %>%
  mutate(scanInd = 1:nrow(.)) %>%
  filter(barrelName %in% trainBarrels) %>%
  pull(scanName)

# future:::ClusterRegistry("stop")
# 
# future::plan(future::multisession(workers = future::availableCores() - 9))

# furrr::future_walk
walk(list(
  # NA, #calculated previously -- saved to data/cmcs_notFiltered.RData
  # list("lp",16), #calculated previously -- saved to data/trainScans_filtered_lp_16.RData
  # list("lp",32),
  # list("lp",48),
  # list("lp",64),
  list("bp",c(16,250)),
  list("bp",c(32,250)),
  list("bp",c(48,250)),
  list("bp",c(64,250)),
  list("bp",c(16,375)),
  list("bp",c(32,375)),
  list("bp",c(48,375)),
  list("bp",c(64,375)),
  c("bp",c(16,500)), #calculated previously -- saved to data/cmcs_filtered.RData
  list("bp",c(32,500)),
  list("bp",c(48,500)),
  list("bp",c(64,500)),
  # list("lp",20),
  # list("lp",30),
  # list("lp",40),
  # list("lp",50),
  list("bp",c(20,250)),
  list("bp",c(20,300)),
  list("bp",c(20,350)),
  list("bp",c(20,400)),
  list("bp",c(20,450)),
  list("bp",c(30,250)),
  list("bp",c(30,300)),
  list("bp",c(30,350)),
  list("bp",c(30,400)),
  list("bp",c(30,450)),
  list("bp",c(40,250)),
  list("bp",c(40,300)),
  list("bp",c(40,350)),
  list("bp",c(40,400)),
  list("bp",c(40,450)),
  list("bp",c(50,250)),
  list("bp",c(50,300)),
  list("bp",c(50,350)),
  list("bp",c(50,400)),
  list("bp",c(50,450))
  ),
  function(params){
    
    print(paste0("data/trainScans_filtered_",params[[1]],"_",paste0(params[[2]],collapse = "_"),".RData"))
    
    future:::ClusterRegistry("stop")
    
    future::plan(future::multisession(workers = future::availableCores() - 6))
    
    trainScans_processed <- 
      furrr::future_map(trainFileNames,
                       function(file){
                         
                         dat <- x3p_read(file)
                         
                         dat <- dat %>%
                           preProcess_crop(region = "exterior",
                                           radiusOffset = -30) %>%
                           preProcess_crop(region = "interior",
                                           radiusOffset = 200) %>%
                           preProcess_removeTrend(statistic = "quantile",
                                                  tau = .5,
                                                  method = "fn") %>%
                           preProcess_gaussFilter(filtertype = params[[1]],wavelength = params[[2]]) %>%
                           x3ptools::sample_x3p()
                         
                         dat <- dat %>%
                           preProcess_cropWS(robust = FALSE,
                                             croppingProp = .5)
                         
                         dat$mask <- NULL
                         
                         return(dat)
                         
                       })
    
    future:::ClusterRegistry("stop")
    
    future::plan(future::multisession(workers = future::availableCores() - 6))
    
    CMCs <- 
      furrr::future_map_dfr(1:(length(trainScans_processed) - 1),
                        function(refInd){
                          map_dfr((refInd + 1):length(trainScans_processed),
                                  function(targInd){
                                    
                                    ref <- trainScans_processed[[refInd]]
                                    targ <- trainScans_processed[[targInd]]
                                    
                                    CMCs <- purrr::map_dfr(seq(-30,30,by = 3),
                                                           ~ comparison_allTogether(reference = ref,
                                                                                    target = targ,
                                                                                    theta = .))  %>%
                                      mutate(originalMethodClassif = decision_CMC(cellIndex = cellIndex,
                                                                                  x = x,
                                                                                  y = y,
                                                                                  theta = theta,
                                                                                  corr = pairwiseCompCor,
                                                                                  xThresh = 20,
                                                                                  thetaThresh = 6,
                                                                                  corrThresh = .5)) %>%
                                      mutate(comparisonName = paste0(trainScanNames[refInd]," vs. ",trainScanNames[targInd]))
                                    
                                  })
                        })
    
    save(CMCs,file = paste0("data/trainScans_filtered_",params[[1]],"_",paste0(params[[2]],collapse = "_"),".RData"))
    
  })
```



```{r}
matchDictionary <- map_dfr(1:10,
                           function(barrel){
                             
                             data.frame(scanName = list.files(paste0("~/nbtrdScans/fadulScans/Fadul_",barrel),
                                                              pattern = ".x3p",include.dirs = FALSE,recursive = TRUE)) %>%
                               mutate(scanName = str_remove(str_remove(scanName,"cc/"),".x3p"),
                                      barrelName = barrel)
                             
                           })
```

```{r}
trainScans_allCMCs <- map_dfr(list.files("data/",full.names = TRUE,pattern = "trainScans"),
        function(fileName){
          
          fileSplit <- str_split(fileName,"_")[[1]]
          
          fileSplit <- str_remove(fileSplit[3:length(fileSplit)],".RData")
          
          filterType <- fileSplit[1]
          
          filterParams <- paste0(fileSplit[-1],collapse = ", ")
          
          load(fileName)
          
          return(CMCs %>%
                   mutate(filterType = filterType,
                          filterParams = filterParams))
          
        })
```


```{r}
pltData <- trainScans_allCMCs %>%
  mutate(filterName = paste0(filterType," - ",filterParams)) %>%
  select(-c(reference,target)) %>%
  group_by(comparisonName,filterName) %>%
  summarise(cmcCount = sum(originalMethodClassif == "CMC")) %>%
  ungroup() %>%
  tidyr::separate(col = comparisonName,into = c("reference","target"),sep = " vs. ",remove = TRUE) %>%
  left_join(matchDictionary,by = c("reference" = "scanName")) %>%
  rename(refBarrel = barrelName) %>%
  left_join(matchDictionary,by = c("target" = "scanName")) %>%
  rename(targBarrel = barrelName) %>%
  mutate(type = ifelse(refBarrel == targBarrel,"match","non-match")) %>%
  group_by(filterName) %>%
  group_split() %>%
  map_dfr(~ calcVarianceRatio(.)) %>%
  select(filterName,varRatio) %>%
  distinct() %>%
  tidyr::separate(filterName,into = c("filterType","filterParams"),sep = " - ")

plt <- pltData %>%
  mutate(filterType = ifelse(filterType == "NA","none",filterType))  %>%
  filter(filterParams %in% c("notFiltered","16","32","48","64","16, 250", "32, 250", "48, 250", "64, 250", "16, 375", "32, 375", "48, 375", "64, 375", "16, 500","32, 500","48, 500","64, 500")) %>%
  mutate(filterType = factor(filterType,levels = c("none","lp","bp"),labels = c("No\nFilter","Lowpass","Bandpass"))) %>%
  mutate(filterParams = ifelse(filterParams == "notFiltered","No Params.",filterParams)) %>%
  mutate(filterParams = factor(filterParams),
         maxParams = ifelse(varRatio == max(varRatio),TRUE,FALSE)) %>%
  ggplot(aes(y = filterParams,x = varRatio,colour = maxParams)) +
  geom_point(size = 2) +
  geom_segment(aes(xend = 0,yend = filterParams,size = maxParams),alpha = .5) +
  facet_grid(rows = vars(filterType),drop = TRUE,scales = "free_y",space = "free") +
  theme_bw() +
  coord_cartesian() +
  scale_x_continuous(limits = c(0,17.5),expand = expansion(0)) +
  theme(strip.text = element_text(),
        legend.position = "none",
        panel.grid.major.y = element_blank()) +
  scale_colour_manual(values = c("gray0","red")) +
  scale_size_manual(values = c(.2,1)) +
  labs(x = "Variance Ratio Value",
       y = "Filter Parameters")

plt

ggsave(filename = "images/varianceRatioPlot.png",plt,width = 7,height = 5)
```


```{r}
matchDictionary <- map_dfr(1:10,
                           function(barrel){
                             
                             data.frame(scanName = list.files(paste0("~/nbtrdScans/fadulScans/Fadul_",barrel),
                                                              pattern = ".x3p",include.dirs = FALSE,recursive = TRUE)) %>%
                               mutate(scanName = str_remove(str_remove(scanName,"cc/"),".x3p"),
                                      barrelName = barrel)
                             
                           })

# having learned the optimal parameters are a bandpass filter with wavelength
# cutoffs of 16 and 250 microns, test these parameters against the test set
testFileNames <- data.frame(fileName = list.files("~/nbtrdScans/fadulScans/",full.names = TRUE,pattern = ".x3p",include.dirs = TRUE,recursive = TRUE)) %>%
  mutate(scanName = str_split(fileName,"/") %>%
           map_chr(~ .[10]) %>%
           str_remove(".x3p")) %>%
  left_join(matchDictionary,by = "scanName") %>%
  arrange(barrelName) %>%
  mutate(scanInd = 1:nrow(.)) %>%
  filter(barrelName %in% testBarrels) %>%
  pull(fileName)

testScanNames <- data.frame(fileName = list.files("~/nbtrdScans/fadulScans/",full.names = TRUE,pattern = ".x3p",include.dirs = TRUE,recursive = TRUE)) %>%
  mutate(scanName = str_split(fileName,"/") %>%
           map_chr(~ .[10]) %>%
           str_remove(".x3p")) %>%
  left_join(matchDictionary,by = "scanName") %>%
  arrange(barrelName) %>%
  mutate(scanInd = 1:nrow(.)) %>%
  filter(barrelName %in% testBarrels) %>%
  pull(scanName)

# future:::ClusterRegistry("stop")
# 
# future::plan(future::multisession(workers = future::availableCores() - 9))

# furrr::future_walk
walk(list(
  # list("bp",c(20,350))
  list("bp",c(48,250)), #optimized above
  list("bp",c(40,400)),#,# song et al. (2014)
  list("lp",c(40)), # tong et al. (2014)
  list("bp",c(16,250)),#song et al. (2018)
  list("bp",c(16,250)) #weller et al. (2012)
),
  function(params){
    
    print(paste0("data/testScans_filtered_",params[[1]],"_",paste0(params[[2]],collapse = "_"),".RData"))
    
    future:::ClusterRegistry("stop")

    future::plan(future::multisession(workers = future::availableCores() - 6))
    
    testScans_processed <- 
      furrr::future_map(
        # map(
          testFileNames,
                       function(file){
                         
                         dat <- x3p_read(file)
                         
                         dat <- dat %>%
                           preProcess_crop(region = "exterior",
                                           radiusOffset = -30) %>%
                           preProcess_crop(region = "interior",
                                           radiusOffset = 200) %>%
                           preProcess_removeTrend(statistic = "quantile",
                                                  tau = .5,
                                                  method = "fn") %>%
                           preProcess_gaussFilter(filtertype = params[[1]],wavelength = params[[2]]) %>%
                           x3ptools::sample_x3p()
                         
                         dat <- dat %>%
                           preProcess_cropWS(robust = FALSE,
                                             croppingProp = .5)
                         
                         dat$mask <- NULL
                         
                         return(dat)
                         
                       })
    
    # return(testScans_processed)
    
    future:::ClusterRegistry("stop")

    future::plan(future::multisession(workers = future::availableCores() - 6))
    
    # CMCs <-
      furrr::future_map_dfr(
        # map_dfr(
          1:(length(testScans_processed) - 1),
                        function(refInd){
                          map_dfr((refInd + 1):length(testScans_processed),
                                  function(targInd){

                                    ref <- testScans_processed[[refInd]]
                                    targ <- testScans_processed[[targInd]]

                                    # print(paste0(ref," vs. ",targ))
                                    
                                    CMCs <- purrr::map_dfr(seq(-30,30,by = 3),
                                                           ~ comparison_allTogether(reference = ref,
                                                                                    target = targ,
                                                                                    theta = .)) %>%
                                      mutate(originalMethodClassif = decision_CMC(cellIndex = cellIndex,
                                                                                  x = x,
                                                                                  y = y,
                                                                                  theta = theta,
                                                                                  corr = pairwiseCompCor,
                                                                                  xThresh = 20,
                                                                                  thetaThresh = 6,
                                                                                  corrThresh = .5)) %>%
                                      mutate(comparisonName = paste0(testScanNames[refInd]," vs. ",testScanNames[targInd]),
                                             filterType = params[[1]],
                                             filterParams = paste0(params[[2]],collapse = ", "))
                                    
                                    save(CMCs,file = paste0("data/testScans_filtered_",params[[1]],"_",paste0(params[[2]],collapse = "_"),"/",paste0(testScanNames[refInd],"_vs_",testScanNames[targInd]),".RData"))

                                  })
                        })

    # save(CMCs,file = paste0("data/testScans_filtered_",params[[1]],"_",paste0(params[[2]],collapse = "_"),"_secondTry.RData"))
    
  })

x3pListPlot(dat[[1]],type = "list")

future:::ClusterRegistry("stop")
```
 
 
```{r}
testScans_allCMCs <- map_dfr(list.files("data/",full.names = TRUE,pattern = "testScans.*RData",include.dirs = FALSE),
        function(fileName){
          
          # fileSplit <- str_split(fileName,"_")[[1]]
          # 
          # fileSplit <- str_remove(fileSplit[3:length(fileSplit)],".RData")
          # 
          # filterType <- fileSplit[1]
          # 
          # filterParams <- paste0(fileSplit[-1],collapse = ", ")
          
          load(fileName)
          
          return(CMCs)
          
        })
```


```{r}
pltData <- testScans_allCMCs %>%
  mutate(filterName = paste0(filterType," - ",filterParams)) %>%
  group_by(comparisonName,filterName) %>%
  summarise(cmcCount = sum(originalMethodClassif == "CMC")) %>%
  ungroup() %>%
  tidyr::separate(col = comparisonName,into = c("reference","target"),sep = " vs. ",remove = TRUE) %>%
  left_join(matchDictionary,by = c("reference" = "scanName")) %>%
  rename(refBarrel = barrelName) %>%
  left_join(matchDictionary,by = c("target" = "scanName")) %>%
  rename(targBarrel = barrelName) %>%
  mutate(type = ifelse(refBarrel == targBarrel,"match","non-match")) %>%
  group_by(filterName) %>%
  group_split() %>%
  map_dfr(~ calcVarianceRatio(.)) %>%
  select(filterName,varRatio) %>%
  distinct() %>%
  tidyr::separate(filterName,into = c("filterType","filterParams"),sep = " - ")

plt <- pltData %>%
  mutate(filterType = ifelse(filterType == "NA","none",filterType))  %>%
  filter(filterParams != "20, 350") %>%
  # mutate(filterType = ifelse(filterParams == "48, 250","bp ",filterType)) %>%
  mutate(filterType = factor(filterType,levels = c("none","bp","lp"),labels = c("No\nFilter","Bandpass","Lowpass"))) %>%
  mutate(filterParams = ifelse(filterParams == "notFiltered","No Params.",filterParams)) %>%
  mutate(filterParams = factor(filterParams,levels = c("40","16, 250","40, 400","48, 250"),
                               labels = c("40\nTong et al. (2014)",
                                          "16, 250\nWeller et al. (2012)\nSong et al. (2018)",
                                          "40, 400\nSong et al. (2014)",
                                          "48, 250\nOptimized")),
         maxParams = ifelse(varRatio == max(varRatio),TRUE,FALSE)) %>%
  # filter(filterParams == "48, 250\nOptimized") %>%
  # filter(filterParams != "48, 250\nOptimized") %>%
  ggplot(aes(y = filterParams,x = varRatio,colour = maxParams)) +
  geom_point(size = 2) +
  geom_segment(aes(xend = 0,yend = filterParams,size = maxParams),alpha = .5) +
  facet_grid(rows = vars(filterType),drop = TRUE,scales = "free_y",space = "free") +
  theme_bw() +
  coord_cartesian() +
  scale_x_continuous(limits = c(0,17.5),expand = expansion(0)) +
  theme(strip.text = element_text(),
        legend.position = "none",
        panel.grid.major.y = element_blank()
        # ,axis.title.y = element_blank()
        ) +
  scale_colour_manual(values = c("gray0","red")) +
  scale_size_manual(values = c(.2,1)) +
  labs(x = "Variance Ratio Value"
       ,y = "Filter Parameters"
       )

plt

ggsave(filename = "images/varianceRatioPlot_test.png",plt,width = 7,height = 2.75)
```

```{r}
# visualize an example of the variance ratio value on some train data
trainScans_allCMCs %>%
  mutate(filterName = paste0(filterType," - ",filterParams)) %>%
  select(-c(reference,target)) %>%
  group_by(comparisonName,filterName) %>%
  summarise(cmcCount = sum(originalMethodClassif == "CMC")) %>%
  ungroup() %>%
  tidyr::separate(col = comparisonName,into = c("reference","target"),sep = " vs. ",remove = TRUE) %>%
  left_join(matchDictionary,by = c("reference" = "scanName")) %>%
  rename(refBarrel = barrelName) %>%
  left_join(matchDictionary,by = c("target" = "scanName")) %>%
  rename(targBarrel = barrelName) %>%
  mutate(type = ifelse(refBarrel == targBarrel,"match","non-match")) %>%
  group_by(filterName) %>%
  group_split() %>%
  map_dfr(~ calcVarianceRatio(.)) %>%
  tidyr::separate(filterName,into = c("filterType","filterParams"),sep = " - ",remove = FALSE) %>%
  filter(filterParams %in% c("notFiltered",
                             # "16","32","48","64",
                             # "16, 250", "32, 250", "48, 250", "64, 250", "16, 375",
                             "32, 375"
                             # ,"48, 375", "64, 375", "16, 500","32, 500", "48, 500","64, 500"
  )) %>%
  group_by(filterName,type,varRatio,cmcCount) %>%
  tally() %>%
  mutate(prop = n/sum(n)) %>%
  rename(Type = type) %>%
  mutate(filterName = factor(filterName,
                             levels = rev(c("NA - notFiltered","bp - 32, 375")),
                             labels = rev(c("Not Filtered","Bandpass - 32, 375")))) %>%
  ggplot(aes(x = cmcCount,y = prop,fill = Type)) +
  geom_bar(stat = "identity") +
  facet_wrap(~filterName,ncol = 1) +
  theme_bw() +
  labs(x = "CMC Count",
       y = "Relative Frequency") +
  scale_fill_manual(values = c("#40B0A6","#E1BE6A")) +
  theme(legend.position = "bottom") +
  geom_label(data= trainScans_allCMCs %>%
               mutate(filterName = paste0(filterType," - ",filterParams)) %>%
               select(-c(reference,target)) %>%
               group_by(comparisonName,filterName) %>%
               summarise(cmcCount = sum(originalMethodClassif == "CMC")) %>%
               ungroup() %>%
               tidyr::separate(col = comparisonName,into = c("reference","target"),sep = " vs. ",remove = TRUE) %>%
               left_join(matchDictionary,by = c("reference" = "scanName")) %>%
               rename(refBarrel = barrelName) %>%
               left_join(matchDictionary,by = c("target" = "scanName")) %>%
               rename(targBarrel = barrelName) %>%
               mutate(type = ifelse(refBarrel == targBarrel,"match","non-match")) %>%
               tidyr::separate(filterName,into = c("filterType","filterParams"),sep = " - ",remove = FALSE) %>%
               filter(filterParams %in% c("notFiltered",
                                          # "16","32","48","64",
                                          # "16, 250", "32, 250", "48, 250", "64, 250", "16, 375",
                                          "32, 375"
                                          # ,"48, 375", "64, 375", "16, 500","32, 500", "48, 500","64, 500"
               )) %>%
               group_by(filterName) %>%
               group_split() %>%
               map_dfr(~ calcVarianceRatio(.)) %>%
               select(filterName,varRatio) %>%
               distinct() %>%
               mutate(filterName = factor(filterName,
                                          levels = c("NA - notFiltered","bp - 32, 375"),
                                          labels = c("Not Filtered","Bandpass - 32, 375"))),
             aes(x = 12,y = .45,label = paste0("Variance Ratio: ",round(varRatio,2))),check_overlap = TRUE,fill = NA)
```
































